### ISSUE TITLE
Remove duplicate posts in "media coverage" and "blog" page

### ISSUE THREAD

**Issue by Kevinwochan** [ocius/website#102]
For example, these two posts.
![image](https://user-images.githubusercontent.com/18486383/71144105-f4fb1a80-2270-11ea-82c9-42a6e90d8080.png)

![image](https://user-images.githubusercontent.com/18486383/71144119-03e1cd00-2271-11ea-8efc-61bb8f667b86.png)

Best not to delete those mark down files but move it somewhere else so we can archive them properly in the future.

**Comment by r007** [comment]
Done, I implemented it. If you want to archive an article, simply add the "draft: true" to the header.

![draftpng](https://user-images.githubusercontent.com/78280/71416247-1301ba00-2679-11ea-946f-ee1f2f9b5f23.png)

The article won't be visible on the blog page (but the markdown file still will be available).
