### ISSUE TITLE
Support case of one drone

### ISSUE THREAD

**Issue by thomasdane** [ocius/website#104]
We built the live page on the assumption there are at least two drones. When there is a single drone online, the site is breaking. 

<img width="593" alt="twoDrones" src="https://user-images.githubusercontent.com/2957318/72496988-30412880-37e0-11ea-9ba6-ce620a6551fb.PNG">

This a problem with the API design: 

<img width="409" alt="duplicates" src="https://user-images.githubusercontent.com/2957318/72497148-9b8afa80-37e0-11ea-894a-134eb7c1f72b.PNG">

I will filter out duplicate drones

**Comment by thomasdane** [comment]
This is not fixed @Kevinwochan @r007 Please verify https://ocius.com.au/live/

**Comment by Kevinwochan** [comment]
@thomasdane looks good!
