### ISSUE TITLE
Create sitemap for SEO

### ISSUE THREAD

**Issue by Kevinwochan** [ocius/website#107]
https://support.google.com/webmasters/answer/156184?hl=en&ref_topic=4581190&visit_id=637149002036269621-2191040238&rd=1

**Comment by r007** [comment]
Done. Sitemap was added, it will appear in production build after
```
gatsby build
```
Sitemap URL: https://hostname/sitemap.xml

Not perfect, for example last modification date is the same for all URLs, but should do the job.

![sitemap](https://user-images.githubusercontent.com/78280/72906965-86681b80-3d4c-11ea-89b2-2450a4604e98.png)

**Comment by Kevinwochan** [comment]
Just an update from my end, Look good! Google has indexed these 
![Screenshot from 2020-02-13 15-41-51](https://user-images.githubusercontent.com/18486383/74402133-7dfc8f80-4e77-11ea-88b4-be2132291055.png)

**Comment by r007** [comment]
@Kevinwochan nice! Let me know if you need any adjustments.
