### ISSUE TITLE
Add article to Media Coverage Page

### ISSUE THREAD

**Issue by Kevinwochan** [ocius/website#109]
https://news.navy.gov.au/en/202001/Fleet/5709/Sea-trials-demonstrate-new-capability-to-manage-AUVs.htm#.XjLE1nlxUwA

**Comment by Kevinwochan** [comment]
As well as https://www.amsa.gov.au/news-community/news-and-media-releases/australian-autonomous-vessel-forum-2019

**Comment by r007** [comment]
Done, added them both, take a look:
https://sergey.d3fhwa1e0f950h.amplifyapp.com/media-coverage

Same password. Now all the links are sorted by date starting from the most recent. Feel free to close if you're fine with these changes.
