### ISSUE TITLE
Convert News articles into Media Coverage post

### ISSUE THREAD

**Issue by Kevinwochan** [ocius/website#113]
These posts should be set to "draft" and a separate card for each link should be added to the Media Coverage page.

- https://ocius.com.au/blog/ADF-at-risk-of-being-left-behind/
- https://sergey.d3fhwa1e0f950h.amplifyapp.com/blog/bob-in-the-news/
- https://ocius.com.au/blog/abc-news-navy-explores-use-of-autonomous-vehicles-for-dangerous-dirty-and-dull-work/
- https://ocius.com.au/blog/ocius-bluebottle-on-9news-sydney/
- https://ocius.com.au/blog/ociuschristeningadm/
- https://ocius.com.au/blog/ociusadm/

**Comment by r007** [comment]
Done. All the posts was set to draft and moved to media coverage page. Please check if I did it correctly or not:
https://sergey.d3fhwa1e0f950h.amplifyapp.com/media-coverage

Closing it for now.
