### ISSUE TITLE
Make the LIVE page menu more distinguishable on mobile

### ISSUE THREAD

**Issue by Kevinwochan** [ocius/website#126]
![Screenshot from 2020-02-28 15-37-09](https://user-images.githubusercontent.com/18486383/75510798-39a8ec00-5a40-11ea-9e49-272bb574d915.png)

At the moment the OCIUS logo is very close to the menu button. Robert will sometimes tap on the OCIUS logo instead.

**Comment by Kevinwochan** [comment]
waiting on feedback from UI designer

**Comment by r007** [comment]
Not relevant any more. Closed.
