### ISSUE TITLE
bluebottle overview icon behaviour

### ISSUE THREAD

**Issue by Kevinwochan** [ocius/website#128]
Currently the bluebottle overview icons open a new tab to parts of a video that demonstrates that component.

This is very intrusive to the viewing experience of the entire website.

Possible solutions could be a slider text which changes the main image when an icon is clicked.

**Comment by Kevinwochan** [comment]
This issue is listed as "wontfix" pending a designer to be onboarded.

**Comment by r007** [comment]
Fixed in the new, redesigned version of the website.
