### ISSUE TITLE
Inconsistent map info

### ISSUE THREAD

**Issue by Kevinwochan** [ocius/website#136]
My windows machine displays a trail but my linux machine and mobile phone do not.
I opened the page on each device at around the same time (5 minutes).
![image](https://user-images.githubusercontent.com/18486383/80431590-342f2b80-8935-11ea-941e-3af8c1de758c.png)

**Comment by Kevinwochan** [comment]
![image](https://user-images.githubusercontent.com/18486383/80431633-4f9a3680-8935-11ea-8cdf-3ed383f999a1.png)

**Comment by r007** [comment]
Hey @Kevinwochan. I've been using Linux for whole time while I developed this page. Never had any issues with trails. The trail was made using [Polyline component](https://developers.google.com/maps/documentation/javascript/examples/polyline-simple?hl=ru) and is provided by Google itself. I don't think that Google would miss something obvious like cross browser issue. Plus, trail data is shown for last hour only. So if drones are standing for whole hour still, the trail will disappear.

**Comment by Kevinwochan** [comment]
@r007 yes it's probably not OS issue, i just thought i'd give as much information as possible.

It may have been my devices timing out on fetching the trail data. I'll post more info if it does happen again.

**Comment by Kevinwochan** [comment]
I havent been able to replicate this, closing this issue
