### ISSUE TITLE
Renaming info panel Sensor Data and Power Status

### ISSUE THREAD

**Issue by Kevinwochan** [ocius/website#140]
![Screenshot from 2020-04-29 11-30-40](https://user-images.githubusercontent.com/18486383/80553361-eb4aa600-8a0c-11ea-95e8-35deb26881d3.png)

"the menu on the left comes up as Vessel Status as default - can we make the default - Power Monitor."

So "Sensor Data" -> "Vessel Status"
"Power Status" -> "Power Monitor"

**Comment by r007** [comment]
Done, did that. See #137
