### ISSUE TITLE
Handling more statuses for live page

### ISSUE THREAD

**Issue by Kevinwochan** [ocius/website#166]
![image](https://user-images.githubusercontent.com/18486383/86548910-730ade80-bf81-11ea-99f1-9bbd2024e178.png)

Our front end outputs MAV_STATUS_CRITICAL text.  This should be properly formatted like.

![image](https://user-images.githubusercontent.com/18486383/86548941-874edb80-bf81-11ea-96ca-2fe5ceb6d4f7.png)

I'll post a full enum of all possible statuses once i find them.

critical : red
Active: green
anything else: orange

**Comment by r007** [comment]
Check this out #175, here I added more codes according to [MAVlink status table](https://mavlink.io/en/messages/common.html#MAV_STATE).

- Active - green
- Unitialized, calibrating, standby, boot - yellow
-,Critical, emergency, poweroff, termination - red

Should be fixed now.
