### ISSUE TITLE
Graphical display of wind data

### ISSUE THREAD

**Issue by Kevinwochan** [ocius/website#197]
> can we show wind speed and direction as a 'wind rose'

not sure how we'll tackle this.

**Comment by r007** [comment]
@Kevinwochan wind rose is a chart, we can use an existing component, such as
https://www.npmjs.com/package/react-windrose-chart

But it requires a bunch of data for each angle. Maybe something simpler will fit better here...

Another approach is to display the wind map itself.

![intro4](https://user-images.githubusercontent.com/78280/91295822-b5e07a00-e7ac-11ea-92b8-53a217762e88.gif)

**Comment by Kevinwochan** [comment]
Robert has requested this feature again

**Comment by Kevinwochan** [comment]
https://github.com/ocius/website/issues/197

**Comment by LorenzoLeeSolano** [comment]
@r007
Data for the wind direction, wind speed, water current direction and water current speed for each drone are now being served by the api. I've listed the units below.

Wind_speed: metres per second
Wind_direction: degrees TRUE(from north)
Current_speed: metres per second
Current_direction: centi-degrees TRUE(degrees * 100)

Also, see this comment Kevin left on the api repo.
https://github.com/ocius/api/issues/49#issuecomment-770569852

**Comment by r007** [comment]
@LorenzoLeeSolano awesome! Thanks, I'll show it all on the frontend then.

**Comment by r007** [comment]
Done, data has been changed accordingly.

**Comment by LorenzoLeeSolano** [comment]
@r007 
Would it be possible to graphically display this data on the front end?

If a full wind rose is overkill for this amount of data, what do you think about something simpler like a wind rose with only one spoke, or maybe just a wind barb?

I can try and double check with Robert about what he wants it to look like if that would help.

**Comment by r007** [comment]
@LorenzoLeeSolano alright, will try to implement it. But I'll an API key from openweathermap.org to show this kind of data.

**Comment by LorenzoLeeSolano** [comment]
> But I'll need an API key from openweathermap.org


@r007
Is that for additional weather data? 
I think Robert just wants it to be based off whichever USV is currently selected, using the weather data provided by the api for that USV. Is that possible?

**Comment by LorenzoLeeSolano** [comment]
@r007 
Just just updating this with the new info from Robert:
![WindRose](https://user-images.githubusercontent.com/68361987/116226238-17bb0e80-a796-11eb-81a4-e11fd93ae245.png)
He specified a wind rose like the one above, with wind speed and direction in white, and current speed and direction in red.
Do you think it would be possible to achieve this with the wind/current data for a selected USV?

**Comment by r007** [comment]
@LorenzoLeeSolano oh, this looks nice! Of course it is possible, I'll work on it on weekends, I think should not be too hard. Basically just a circle with an arrow.

**Comment by LorenzoLeeSolano** [comment]
>  Can we have Wind speed and current speed in knots in knots (not m/s)
@r007 
Just documenting this here, the wind rose should have wind speed and current speed in knots,
as per Robert's email.

Let me know if I can help clarify anything. Thanks!

**Comment by r007** [comment]
@LorenzoLeeSolano ah... okay, replaced back units. Still working on the rose thing...

**Comment by r007** [comment]
Done. The wind rose is implemented. Need to check if direction is correct.
https://ocius.com.au/live/

**Comment by LorenzoLeeSolano** [comment]
@r007 Looks great!
I think the directions might be off though. See #271
Angles are from north, but I think the arrow's must be pointing west before rotation.

**Comment by r007** [comment]
@LorenzoLeeSolano yeah, I was not exactly sure about directions. But thanks for the correction!

**Comment by r007** [comment]
I guess it can be closed now.
