### ISSUE TITLE
Removing API keys

### ISSUE THREAD

**Issue by Kevinwochan** [ocius/website#202]
> “Please note that you shouldn’t commit .env.* files to your source control and rather use options given by your Continuous Deployment (CD) provider. An example is Netlify with its build environment variables.”

I've fixed up the Amplify side of things, API keys will now be available from the environment variable GATSBY_GOOGLE_MAPS_API_KEY inline with Gatsby's documentation for OS environment variables. https://www.gatsbyjs.com/docs/environment-variables/#additional-environments-staging-test-etc.

**Comment by Kevinwochan** [comment]
API keys are visible client side regardless low priority.

**Comment by r007** [comment]
Nice. I think this can be closed now. Before we used domain restriction as some kind of protection against unauthorized use :)
