### ISSUE TITLE
Convert data to nautical miles

### ISSUE THREAD

**Issue by LorenzoLeeSolano** [ocius/website#254]
From Robert today:
"Can you make the live page read knots?"

**Comment by r007** [comment]
@LorenzoLeeSolano done. Changed as he said. But I'm a little bit confused - is the API data already in knots? Or do I need to convert from m/s to knots? Right now I display it "as is", no conversion is done.

**Comment by LorenzoLeeSolano** [comment]
I'm actually not quite sure what the unconverted units are in. I'd presume they're in knots, but I'll double check next time I talk to Matt.
