### ISSUE TITLE
Displaying map scale

### ISSUE THREAD

**Issue by LorenzoLeeSolano** [ocius/website#259]
> Why not keep it all as is and add a scale for zoom in and out - like on all google maps and see attached screenshot.

![Screen Shot 2021-04-22 at 10 35 43 am](https://user-images.githubusercontent.com/68361987/116228030-20144900-a798-11eb-919a-97fa4ac089a5.png)
How difficult do you think this would be to achieve?

**Comment by r007** [comment]
Not too hard, surely will add.

**Comment by r007** [comment]
Done, added this indicator.

![indicator](https://user-images.githubusercontent.com/78280/118573349-69522a00-b793-11eb-950b-9d7ebd1f4aec.png)

**Comment by r007** [comment]
Modified the style just a little bit as Robert said. Closing the issue now.

![scale](https://user-images.githubusercontent.com/78280/118807057-e1fed680-b8b8-11eb-90f6-54d77d3fc037.png)
