### ISSUE TITLE
Show Air Temperature on the Live page.

### ISSUE THREAD

**Issue by LorenzoLeeSolano** [ocius/website#261]
This can be found under `"Air_temp"` from the API, and should be in the same units as `"Water_temp"`.

Additionally, Robert wants 
**Current Direction**, **Current Speed**,
**Wind Direction**, **Wind Speed**,
to be removed from the side bar, as they'll instead be graphically displayed :).

**Comment by LorenzoLeeSolano** [comment]
@r007 
Would you be happy to do this as well?

**Comment by r007** [comment]
@LorenzoLeeSolano yeah, sure.

**Comment by r007** [comment]
Done, removed everything.
