### ISSUE TITLE
Select a vessel in the side bar when its icon is clicked on the map.

### ISSUE THREAD

**Issue by LorenzoLeeSolano** [ocius/website#279]
Request from Robert:

> We have it so if you click on name of boat in menu on left - the map zooms in on that boat and camera - fantastic! 
> OK the big question is can we also have it other way round also so if you select a boat on the map - the data in the menu changes automatically to that boat??

@r007 Do you think this is doable?

In other words, when a vessels icon on the map is clicked, that vessel is selected in the side bar and its information is displayed.

**Comment by LorenzoLeeSolano** [comment]
> ii) If a person clicks on a boat on the map please make the menu on left AND the wind/current rose apply to that boat!
Robert requested this feature again today.

**Comment by r007** [comment]
@LorenzoLeeSolano oh... I see now. Will to fix today.

**Comment by r007** [comment]
Phew, this is fixed now.
