### ISSUE TITLE
Images unavailable at default zoom level.

### ISSUE THREAD

**Issue by LorenzoLeeSolano** [ocius/website#292]
@r007 
It looks like we're zooming in past the maximum zoom for satellite images in some areas:
![Screen Shot 2021-10-04 at 12 30 21](https://user-images.githubusercontent.com/68361987/135781356-56cb6f21-8441-4826-8b98-b457a473f81c.png)
Can we limit this based on[ `google.maps.MaxZoomService`](https://developers.google.com/maps/documentation/javascript/maxzoom): `getMaxZoomAtLatLng()`?

**Comment by r007** [comment]
@LorenzoLeeSolano good idea! Done, issue with max zoom is fixed (https://github.com/ocius/website/pull/294).
