### ISSUE TITLE
Boat speed half of actual value

### ISSUE THREAD

**Issue by LorenzoLeeSolano** [ocius/website#316]
@r007 
https://github.com/ocius/website/blob/f38d6d1cd4d84bf65150b70d91ee2d8378326787/src/components/InfoPanel/VesselStatus.js#L213

I think this value needs to be converted from m/s to knots (multiplied by 1.94384).

**Comment by r007** [comment]
@LorenzoLeeSolano Ah, I dunno. I already changed this value several times. I am confused, let me check...

**Comment by r007** [comment]
Done, added conversion to knots. https://github.com/ocius/website/pull/319
