### ISSUE TITLE
No scale on mobile Live page.

### ISSUE THREAD

**Issue by LorenzoLeeSolano** [ocius/website#323]
#### The scale doesn't seem to be visible on the mobile version of the live page: 
![247232580_408935520681534_5129350468382398757_n](https://user-images.githubusercontent.com/68361987/138555206-6742ec15-e089-42f9-b780-02a6303929a7.jpg)

**Comment by r007** [comment]
Fixed. I changed the way container height is being calculated. It happens because browser controls are not taken into account in vh units.

Link to article:
https://css-tricks.com/the-trick-to-viewport-units-on-mobile/
