### ISSUE TITLE
Popup does not close when clicking the map

### ISSUE THREAD

**Issue by thomasdane** [ocius/website#47]
**Steps to reproduce**

Mobile: 
- Open the sidebar or the camera popup
- Click the map

Desktop: 
- Open a camera popup

**Expected**

The sidebar/popup should close

**Actual**

It does not close

**Comment by thomasdane** [comment]
This is now fixed for the sidebar. Thanks @r007 ! We are discussing a solution for the camera popup.

**Comment by thomasdane** [comment]
@r007 if the solution to this is difficult, we could make the 'x' in the popup larger by using the different popup types you mentioned.

**Comment by r007** [comment]
Yes, but there is one "but"... InfoBubble and InfoBox are third party libraries which are built on top of native OverlayView. InfoBubble has only [node port](https://github.com/Anton-Nikishkin/node-js-info-bubble) and needs to be ported on React. It's no longer maintained at the moment. Though InfoBox has React port as much as I know...

**Comment by r007** [comment]
Done, I come up with an interesting solution. It is fixed now. I'm closing the issue.
