### ISSUE TITLE
Text formatting broken on desktop

### ISSUE THREAD

**Issue by thomasdane** [ocius/website#48]
**Steps to reproduce**

On desktop:
- Go to https://www.ocius.cloud/live/
- Increase zoom (for me on chromium on linux it still happens at 90% zoom)

**Expected**
- Side bar should expand to accommodate text

**Actual**

<img width="193" alt="formattingWhenZoomed" src="https://user-images.githubusercontent.com/2957318/66256775-1eaea600-e746-11e9-8470-d243f3055092.PNG">

**Comment by r007** [comment]
Done. Should be fixed now. Take a look.
