### ISSUE TITLE
Battery info obscured by browser nav

### ISSUE THREAD

**Issue by thomasdane** [ocius/website#51]
**Steps to reproduce**

- On mobile, using chrome on iOS or brave on android, open the side bar

**Expected**

Can view second battery 

**Actual**

Chrome iOS
![Screenshot_20191006-130143](https://user-images.githubusercontent.com/2957318/66275034-aaedc580-e839-11e9-83b7-8b9d3cbdd6df.png)

**Brave android**
![Screenshot_20191006-120203 (1)](https://user-images.githubusercontent.com/2957318/66275041-b8a34b00-e839-11e9-8dc8-5b797c9a99fd.png)

**Chrome desktop**
<img width="222" alt="sidebarDesktop" src="https://user-images.githubusercontent.com/2957318/66289158-a274a980-e890-11e9-9296-85d006d1fb26.PNG">

**Comment by r007** [comment]
Check out, should be fixed by now. You should be able to scroll the sidebar.

**Comment by thomasdane** [comment]
Great stuff @r007
