### ISSUE TITLE
Toggling between drones triggers camera popup

### ISSUE THREAD

**Issue by thomasdane** [ocius/website#53]
**Steps to reproduce**

- Go to live page
- Open sidebar
- Use drop down to switch between drones

**Expected**

- Sensor data changes

**Actual**

- Sensor data changes AND camera popup opens behind sidebar

**Comment by r007** [comment]
Done, the InfoWindow won't show off on small screens (<= 1056px) if user selected another drone in dropdown. But it will center and zoom the map to draw attention to that drone. Is that what you wanted? On big screens it will open popup as usual.

**Comment by thomasdane** [comment]
This is great @r007 thanks so much
