### ISSUE TITLE
Camera popup loads off screen

### ISSUE THREAD

**Issue by thomasdane** [ocius/website#54]
**Steps to reproduce**

- Go to live page
- Click on drone to open popup

**Expected**

- Full image is visible

**Actual**

- Top of image loads offscreen

<img width="480" alt="cameraOffScreen" src="https://user-images.githubusercontent.com/2957318/66289357-4fe7bd00-e891-11e9-8612-2916bd982394.PNG">

**Comment by r007** [comment]
Can you elaborate, please? On which devices it happens? I can't reproduce it on local machine. Every time I click on marker, the screen is centered so popup never really go off the screen.

**Comment by thomasdane** [comment]
Thanks Sergey. Sorry for not providing more detail. This is a low priority. I'll close for now but I can re-open closer to February if we have time.
