### ISSUE TITLE
Add mobile nave to live page

### ISSUE THREAD

**Issue by thomasdane** [ocius/website#59]
Currently on mobile, when you navigate to the live page, you lose the nav tabs at the bottom of the screen. This breaks flow, and means the user cannot progress through the site unless they hit the back button. 

Could we please add the mobile nav to the live page?

**Comment by r007** [comment]
I can, but are you sure it's a good idea? The bottom nav will shrink the visual space even more.

**Comment by r007** [comment]
Done, added mobile nav to live page.
