### ISSUE TITLE
Make mobile nav the same size as rest of site

### ISSUE THREAD

**Issue by thomasdane** [ocius/website#60]
**Steps to reproduce**

- Go to the homepage on mobile
- Note the size of the logo and the height of the div containing the logo
- Go tot the live page on mobile
- Note the size of the logo and the height of the div containing the logo

**Expected**

- Logo and div are the same dimensions

**Actual**

- Mobile is smaller. 

![Screenshot_20191008-174800](https://user-images.githubusercontent.com/2957318/66443483-23988180-e9f4-11e9-9952-126e0b750b9d.png)

vs

![Screenshot_20191008-174808](https://user-images.githubusercontent.com/2957318/66443489-27c49f00-e9f4-11e9-96cd-34889136aab0.png)

**Comment by r007** [comment]
Refactored that part, now they both have the same size.
