### ISSUE TITLE
Make focus around drone names same as focus on rest of site

### ISSUE THREAD

**Issue by thomasdane** [ocius/website#61]
**Steps to reproduce**

- On mobile, open side of live page
- Click drone name to change drones
- Notice focus color (default link blue)

**Expected**

- Focus color is light blue used on rest of site

**Actual**

- Focus color is default link blue

![Screenshot_20191008-175244](https://user-images.githubusercontent.com/2957318/66443721-fdbfac80-e9f4-11e9-866c-fc84695ca045.png)

**Comment by r007** [comment]
Okay, did that.
