### ISSUE TITLE
Live Page is blank

### ISSUE THREAD

**Issue by matthewmcgill** [ocius/website#63]
The live page is currently blank.  No detail on any boats.  Clicking through to Advanced page show data getting to the public server but new Live page isn't showing it.  No errors reported in the console.

**Comment by thomasdane** [comment]
Hi @matthewmcgill thanks so much for raising this! Good spot - after the mission/Pac2019 was over, I turned off the fetching of new data. I've turned it back on, but on a 30 minute interval. You should see new data flowing through now. For future reference, here is the endpoint the frontend uses to get new data https://api.ocius.com.au/drones
