### ISSUE TITLE
Improve homepage performance

### ISSUE THREAD

**Issue by thomasdane** [ocius/website#70]
If you navigate to 

https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://ocius.com.au

You can see the performance of our homepage. 

- Under performance, the main issues are JS execution time and main thread work. Can we address these? 
- It also shows that browser errors were logged to the console. Can we fix that? 
- ~~Finally, it looks like we are not caching our images? The response headers contain 'must-revalidate' and a max age of 0~~.  It also appears that we are loading the same image twice? Screenshot attached

<img width="862" alt="caching" src="https://user-images.githubusercontent.com/2957318/67217587-d0520600-f3d9-11e9-8a3b-8069a967f62d.PNG">

As you can see, it appears the image 'drone_boat_32.jpg' is loaded twice?

**Comment by thomasdane** [comment]
The cache-control headers are now fixed - set to `public,max-age=31536000,immutable`. I used the amplify custom headers discussed here https://forums.aws.amazon.com/message.jspa?messageID=909307#909307

**Comment by r007** [comment]
The JS execution time & main thread work can only be reduced by dynamic code splitting, see [loadable-components](https://dev.to/itmayziii/better-performance-using-dynamic-code-splitting-in-gatsby-with-loadable-components-6am). Or even [gatsby-plugin-no-javascript](https://www.gatsbyjs.org/packages/gatsby-plugin-no-javascript/), which is a bit extreme.

Okay, will remove errors from console.

I don't know, need to check.

**Comment by r007** [comment]
Alright. Almost done, here are some of the changes I've made:

- Added code splitting by components in critical places (using loadable-components).
- Removed **lottie** from dependencies (replaced with custom loading spinner).
- Reduced bundle size by importing only one function from '**lodash**'.
- Reduced bundle size by importing only Header/LeftNav from '**carbon-components**'.

By inspecting import costs I figured out that **carbon-components** adds a crazy amount of JS code to bundle (about 1,5 MB uncompressed / 124,94 KB gzipped).

![dropdown](https://user-images.githubusercontent.com/78280/70496610-9d023c80-1b29-11ea-87a9-7436c5621539.png)

And there is no way to avoid that. I plan to get rid of carbon-components, it makes no sense to keep 1,5 MB of data for just one dropdown. Will keep you informed.

**Comment by r007** [comment]
Filled a bug report on carbon-components-react https://github.com/carbon-design-system/carbon/issues/4847 Will be waiting for an update.

**Comment by thomasdane** [comment]
Amazing work Sergey! Thankso so much.

**Comment by r007** [comment]
@thomasdane I think we can close this issue. The biggest bundle size was on "LIVE" page, I reduced it from 1.7-1.5 MB to 474 KB. I hope IBM developers will help me to shrink bundle size even more - to ~370 KB. Will be waiting for an update.
