### ISSUE TITLE
On usv page, move the video below the fold

### ISSUE THREAD

**Issue by thomasdane** [ocius/website#99]
If you go to https://ocius.com.au/usv the first thing that loads is a video. 

On mobile especially, this loads slowly and shows white space until it loads. 

Could we please move the video below the fold? So the first thing the user gets is the explanation text, and then if they scroll down they see the video? 

@Kevinwochan please explain this to Robert and get his approval. The header of the page asks a question - we should answer it with text first, and then show the video later. It will improve perceived loading time to have the video below the fold.

**Comment by Kevinwochan** [comment]
Approved by Robert

**Comment by r007** [comment]
@thomasdane we can replace YouTube video with [Video.js](https://videojs.com/city) player. YouTube video can be used as source. Alternatively, video can be hosted on S3 bucket with Cloudfront distribution. It could improve the speed. Just sayin'

**Comment by thomasdane** [comment]
@r007 great suggestions for the next iteration! In the mean time, @Kevinwochan can you still raise a PR to move the video below the fold? We can investigate the other options after.

**Comment by r007** [comment]
A pull request was raised, I think we can close this issue. Thanks @Kevinwochan!
